// Background Service Worker for Edge AI PDF Translator
// Powered by NVIDIA Nemotron 3.5 Lightning (nvidia/nemotron-3.5-lightning-30b-a3b)
// Features Structured JSON Schema & Reasoning Filter

const NVIDIA_API_URL = 'https://integrate.api.nvidia.com/v1/chat/completions';
const DEFAULT_MODEL = 'nvidia/nemotron-3.5-lightning-30b-a3b';

chrome.runtime.onInstalled.addListener(() => {
  // Set default settings if not already stored
  chrome.storage.local.get(['nvidiaApiKey', 'model', 'targetLang', 'theme', 'autoTranslate'], (res) => {
    const defaults = {};
    if (res.nvidiaApiKey === undefined) defaults.nvidiaApiKey = '';
    // Migrate or set new default model
    if (!res.model || res.model.includes('riva-translate')) {
      defaults.model = DEFAULT_MODEL;
    }
    if (!res.targetLang) defaults.targetLang = 'vi';
    if (!res.theme) defaults.theme = 'light';
    if (res.autoTranslate === undefined) defaults.autoTranslate = true;

    if (Object.keys(defaults).length > 0) {
      chrome.storage.local.set(defaults);
    }
  });

  // Create Context Menus
  chrome.contextMenus.create({
    id: 'open_in_ai_pdf_reader',
    title: 'Mở Trình đọc PDF AI (Nemotron 3.5)',
    contexts: ['action']
  });
});

chrome.contextMenus.onClicked.addListener((info, tab) => {
  if (info.menuItemId === 'open_in_ai_pdf_reader') {
    chrome.tabs.create({
      url: chrome.runtime.getURL('viewer/viewer.html')
    });
  }
});

/**
 * Parses model output conforming to structured JSON schema and strips reasoning tags (<think>...</think>)
 */
function extractCleanTranslation(rawContent) {
  if (!rawContent) return '';

  // 1. Remove reasoning / thinking tags if generated by MoE reasoning models
  let cleaned = rawContent.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

  // 2. Remove markdown code fences if present (```json ... ```)
  cleaned = cleaned.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();

  // 3. Parse JSON schema
  try {
    const parsed = JSON.parse(cleaned);
    if (parsed && typeof parsed.translation === 'string') {
      return parsed.translation.trim();
    }
    // Check other common keys
    for (const key of ['result', 'translated', 'text', 'output']) {
      if (parsed && typeof parsed[key] === 'string') {
        return parsed[key].trim();
      }
    }
    // If dictionary with values
    const values = Object.values(parsed);
    for (const val of values) {
      if (typeof val === 'string' && val.trim().length > 0) {
        return val.trim();
      }
    }
  } catch (e) {
    // Regex extract if json is slightly malformed
    const match = cleaned.match(/"translation"\s*:\s*"((?:[^"\\]|\\.)*)"/);
    if (match && match[1]) {
      try {
        return JSON.parse(`"${match[1]}"`);
      } catch (_) {
        return match[1];
      }
    }
  }

  // 4. Return cleaned text
  return cleaned;
}

/**
 * Call NVIDIA NIM API with structured schema support and strict timeout
 */
async function callNvidiaApi(apiKey, model, text, targetLang = 'vi', isTest = false) {
  const cleanKey = (apiKey || '').trim();
  if (!cleanKey) {
    throw new Error('API Key không được để trống.');
  }

  const modelId = model || DEFAULT_MODEL;
  const languageName = targetLang === 'vi' ? 'Vietnamese' : (targetLang === 'en' ? 'English' : targetLang);

  const messages = [
    {
      role: 'system',
      content: isTest
        ? `Translate directly into ${languageName}. Output only the translation.`
        : `You are an expert translator specializing in academic and technical texts. Translate the source text accurately into natural, fluent ${languageName}. Output ONLY the translated text without conversational filler, explanations, or thinking.`
    },
    {
      role: 'user',
      content: isTest
        ? `Translate into ${languageName}: "Artificial Intelligence"`
        : `Translate the following text into ${languageName}:\n\n${text}`
    }
  ];

  const payload = {
    model: modelId,
    messages: messages,
    temperature: 0.2,
    top_p: 0.95,
    max_tokens: isTest ? 32 : 2048
  };

  // 35s for test ping, 50s for full document translation
  const timeoutMs = isTest ? 35000 : 50000;
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetch(NVIDIA_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${cleanKey}`
      },
      body: JSON.stringify(payload),
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      const errorJson = await response.json().catch(() => ({}));
      const errorMsg = errorJson.detail || errorJson.error?.message || errorJson.message || `Lỗi HTTP ${response.status}`;
      throw new Error(errorMsg);
    }

    const data = await response.json();
    const rawContent = data.choices?.[0]?.message?.content?.trim();
    if (!rawContent) {
      throw new Error('Mô hình không trả về nội dung.');
    }

    return extractCleanTranslation(rawContent);
  } catch (err) {
    clearTimeout(timeoutId);
    if (err.name === 'AbortError') {
      throw new Error(`Quá thời gian chờ (${Math.round(timeoutMs / 1000)} giây). Máy chủ NVIDIA đang bận hoặc model phản hồi chậm. Bạn có thể thử lại hoặc đổi sang model nhanh hơn như Mistral NeMo 12B.`);
    }
    throw err;
  }
}

/**
 * Google Translate Fallback
 */
async function callFallbackTranslate(text, targetLang = 'vi') {
  const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${targetLang}&dt=t&q=${encodeURIComponent(text)}`;
  const res = await fetch(url);
  const data = await res.json();
  
  let translated = '';
  if (Array.isArray(data) && Array.isArray(data[0])) {
    translated = data[0].map(item => item[0]).join('');
  }
  return translated;
}

// Listen for external messages (e.g., from viewer or popup)
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'OPEN_VIEWER') {
    const url = message.fileUrl 
      ? chrome.runtime.getURL(`viewer/viewer.html?file=${encodeURIComponent(message.fileUrl)}`)
      : chrome.runtime.getURL('viewer/viewer.html');
    chrome.tabs.create({ url });
    sendResponse({ success: true });
    return false;
  }

  if (message.action === 'TEST_NVIDIA_API') {
    (async () => {
      try {
        const usedModel = message.model || DEFAULT_MODEL;
        const result = await callNvidiaApi(
          message.apiKey,
          usedModel,
          'Artificial Intelligence',
          'vi',
          true
        );
        sendResponse({ success: true, translation: result, model: usedModel });
      } catch (err) {
        sendResponse({ success: false, error: err.message });
      }
    })();
    return true; // Keep channel open for async response
  }

  if (message.action === 'TRANSLATE_NVIDIA') {
    (async () => {
      const usedModel = message.model || DEFAULT_MODEL;
      try {
        const result = await callNvidiaApi(
          message.apiKey,
          usedModel,
          message.text,
          message.targetLang || 'vi',
          false
        );

        let modelShortName = usedModel;
        if (usedModel.includes('nemotron-3.5')) modelShortName = 'Nemotron 3.5 (30B)';
        else if (usedModel.includes('gemma-4')) modelShortName = 'Gemma 4 (31B IT)';
        else if (usedModel.includes('deepseek-v4.1')) modelShortName = 'DeepSeek V4.1 Flash';
        else if (usedModel.includes('llama-3.1-nemotron')) modelShortName = 'Nemotron (70B)';
        else if (usedModel.includes('riva-translate')) modelShortName = 'Riva Translate (4B)';

        sendResponse({
          success: true,
          translation: result,
          engine: `NVIDIA ${modelShortName}`,
          model: usedModel
        });
      } catch (err) {
        // Attempt fallback if NVIDIA fails
        try {
          const fallbackResult = await callFallbackTranslate(message.text, message.targetLang || 'vi');
          sendResponse({
            success: true,
            translation: fallbackResult,
            engine: 'Dự phòng (Google Translate)',
            isFallback: true,
            warning: `NVIDIA API lỗi: ${err.message}. Đã chuyển sang bản dịch dự phòng.`
          });
        } catch (fallbackErr) {
          sendResponse({
            success: false,
            error: `NVIDIA: ${err.message}. Dự phòng: ${fallbackErr.message}`
          });
        }
      }
    })();
    return true; // Keep channel open for async response
  }

  if (message.action === 'TRANSLATE_FALLBACK') {
    (async () => {
      try {
        const fallbackResult = await callFallbackTranslate(message.text, message.targetLang || 'vi');
        sendResponse({ success: true, translation: fallbackResult });
      } catch (err) {
        sendResponse({ success: false, error: err.message });
      }
    })();
    return true;
  }

  return false;
});
